name: FlowValve JS
on:
  push:

jobs:
  js:
    runs-on: ubuntu-latest
    steps:
      - id: setup-java
        name: Set up JDK 1.8
        uses: actions/setup-java@v2.4.0
        with:
          java-version: '15'
          distribution: 'zulu'

      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: gradle-wrapper
        name: Gradle Wrapper
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - id: gradle-caches
        name: Gradle Caches
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - id: assemble
        name: Assemble
        run: ./gradlew jsJar

      - id: test
        name: Test
        run: ./gradlew jsTest

      - id: junit-test-result-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: JUnit test results
          path: build/reports/tests/
        if: failure()